version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  build:
    cmds:
      - go build -o app ./src/app.go
  install-migrate:
    cmds:
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
  db:create-migration:
    cmds:
      - migrate create -ext sql -dir ./src/infra/db/migrations -seq {{.CLI_ARGS}}